# Generated by Django 5.2.8 on 2025-11-24 11:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gudang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alamat', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('harga_beli', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('harga_jual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=50, unique=True)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gudang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.gudang')),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=50, unique=True)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('keterangan', models.TextField(blank=True)),
                ('gudang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.gudang')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas', models.IntegerField()),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.pesanan')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.produk')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas', models.IntegerField()),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.pembelian')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.produk')),
            ],
        ),
        migrations.CreateModel(
            name='GudangProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas', models.IntegerField(default=0)),
                ('gudang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok', to='inventory.gudang')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok_per_gudang', to='inventory.produk')),
            ],
            options={
                'unique_together': {('gudang', 'produk')},
            },
        ),
    ]
